/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _00000290331_H_RPCGEN
#define _00000290331_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct sumandos {
	int vector1[10];
	int vector2[10];
};
typedef struct sumandos sumandos;

#define PROGRAMA_SUMA 0x20000001
#define VERSION_SUMA 1

#if defined(__STDC__) || defined(__cplusplus)
#define suma 1
extern  int * suma_1(sumandos *, CLIENT *);
extern  int * suma_1_svc(sumandos *, struct svc_req *);
#define promedio 2
extern  float * promedio_1(sumandos *, CLIENT *);
extern  float * promedio_1_svc(sumandos *, struct svc_req *);
extern int programa_suma_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define suma 1
extern  int * suma_1();
extern  int * suma_1_svc();
#define promedio 2
extern  float * promedio_1();
extern  float * promedio_1_svc();
extern int programa_suma_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_sumandos (XDR *, sumandos*);

#else /* K&R C */
extern bool_t xdr_sumandos ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_00000290331_H_RPCGEN */
