/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "00000290331.h"
#include <math.h>

int *
suma_1_svc(sumandos *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
 	int i;
        int longitud;
        int sumatoria=0;

        longitud=(sizeof(argp->vector1) / sizeof(argp->vector1[1]));

        for(i=0;i<longitud;i++){
                        sumatoria=sumatoria+argp->vector1[i];
                        result=sumatoria;
        }
	return &result;
}

float *
promedio_1_svc(sumandos *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
 	int j;
        float prom=0;
        int longitud;
        int sum=0;

        longitud=sizeof(argp->vector2) / sizeof(argp->vector2[1]);
        for(j=0;j<longitud;j++){
                if(argp->vector2[j] != 0){
                        prom= fabs(argp->vector2[j])+prom;
                        sum++;
                }
        }
        result= prom / sum;
	return &result;
}
