/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "00000290331.h"


void
programa_suma_1(char *host, int longitud, int numeros[])
{
	CLIENT *clnt;
	int  *result_1;
	sumandos  suma_1_arg;
	float  *result_2;
	
	int j=0, i;

        for(i=0;i<10;i++){
                      suma_1_arg.vector1[i]=0;

                      suma_1_arg.vector2[i]=0;
        }

         if ( longitud % 2 == 0 ){

                for(i=0;i<longitud;i++){
                        if(i<longitud/2){
                                suma_1_arg.vector1[i]=numeros[i];
                        }
                        else {
                                suma_1_arg.vector2[j]=numeros[i];
                                j++;
                        }
                }
	}
	else{
                for(i=0;i<longitud-1;i++){
                        if(i<(longitud/2)){
                                suma_1_arg.vector1[i]=numeros[i];
                        }
                        else {
                                suma_1_arg.vector2[j]=numeros[i+1];
                                j++;
                        }
                }
        }
#ifndef	DEBUG
	clnt = clnt_create (host, PROGRAMA_SUMA, VERSION_SUMA, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = suma_1(&suma_1_arg, clnt);
        if (result_1 == (int *) NULL) {
                clnt_perror (clnt, "call failed");
        }
        result_2 = promedio_1(&suma_1_arg, clnt);
        if (result_2 == (float *) NULL) {
                clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */

	printf("la sumatoria es: %d \n",*result_1);
        printf("el promedio es: %f \n",*result_2);


}


int
main (int argc, char *argv[])
{
	char *host;
        int longitud;
        int numeros[20];

        if (argc < 2) {
                printf ("usage: %s server_host\n", argv[0]);
                exit (1);
        }
        host = argv[1];
        longitud = (argc-2);

        for(int i=0;i<longitud;i++){
                numeros[i]=atoi(argv[i+2]);
        }

        programa_suma_1 (host, longitud, numeros);

exit (0);
}
